name: Agent smoke

on:
  workflow_dispatch: {}           # run manually
  push:
    paths:
      - 'scripts/**'              # also run if scripts change

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # If you have a package.json, this installs deps; if not, it's harmless.
      - name: Install deps (best effort)
        run: npm ci || true

      - name: Get latest Preview deployment URL from Vercel
        id: vercel
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          set -euo pipefail
          api="https://api.vercel.com/v6/deployments?projectId=$VERCEL_PROJECT_ID&target=preview&state=READY&limit=1"
          url=$(curl -sS -H "Authorization: Bearer $VERCEL_API_TOKEN" "$api" | jq -r '.deployments[0].url')
          if [ -z "$url" ] || [ "$url" = "null" ]; then
            echo "No READY preview deployment found"; exit 1
          fi
          echo "url=https://$url" >> "$GITHUB_OUTPUT"
          echo "Latest preview is https://$url"

      - name: Run smoke script
        env:
          # The script reads these env vars:
          PREVIEW_URL: ${{ steps.vercel.outputs.url }}
          ORIGIN_ALLOWLIST: ${{ secrets.ORIGIN_ALLOWLIST }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
        run: |
          node scripts/smoke.mjs
