name: Agent smoke

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Resolve latest preview URL
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_TEAM_SLUG: ${{ secrets.VERCEL_TEAM_SLUG }}
        run: |
          node scripts/fetch-latest-preview.mjs > preview.txt
          echo "PREVIEW_URL=$(cat preview.txt)" >> "$GITHUB_ENV"
          echo "Resolved PREVIEW_URL=$(cat preview.txt)"

      - name: Run smoke
        env:
          PREVIEW_URL: ${{ env.PREVIEW_URL }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_BYPASS_TOKEN: ${{ secrets.VERCEL_BYPASS_TOKEN }}
        run: node scripts/agent-smoke.mjs
