name: Agent smoke

on:
  workflow_dispatch:
    inputs:
      preview_url:
        description: 'Optional: override PREVIEW_URL (leave blank to use secret)'
        required: false

permissions:
  contents: read

jobs:
  smoke:
    name: smoke
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # ✅ This makes the workflow robust: if there is no lockfile, we skip install
      - name: Install deps at repo root (only if lockfile exists)
        if: hashFiles('package-lock.json') != '' || hashFiles('npm-shrinkwrap.json') != ''
        run: npm ci

      - name: Install deps in /scripts (only if lockfile exists)
        if: hashFiles('scripts/package-lock.json') != '' || hashFiles('scripts/npm-shrinkwrap.json') != ''
        run: npm ci --prefix scripts

      - name: Show Node info
        run: |
          node -v
          npm -v

      # Run the smoke test script. It will use the env below.
      - name: Run smoke script
        env:
          # Optional manual override if you filled the input when you clicked "Run workflow"
          INPUT_PREVIEW_URL: ${{ github.event.inputs.preview_url }}
          # Secrets you added earlier
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
          BYPASS_URL: ${{ secrets.BYPASS_URL }}
          ORIGIN_ALLOWLIST: ${{ secrets.ORIGIN_ALLOWLIST }}
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          # If you provide an override when dispatching, prefer it; else use the secret
          if [ -n "$INPUT_PREVIEW_URL" ]; then
            export PREVIEW_URL="$INPUT_PREVIEW_URL"
          fi

          # Fail early if we don't have a preview URL
          if [ -z "$PREVIEW_URL" ]; then
            echo "PREVIEW_URL is missing. Set it as a secret or pass an input when running the workflow."
            exit 1
          fi

          # If your script is in /scripts, run from there. Otherwise, from repo root.
          if [ -f "scripts/smoke.mjs" ]; then
            node scripts/smoke.mjs
          elif [ -f "scripts/smoke.js" ]; then
            node scripts/smoke.js
          else
            # fallback if the script is at repo root
            node smoke.mjs || node smoke.js
          fi
