name: Apply Agent Change Set

on:
  workflow_dispatch:
    inputs:
      change_set_url:
        description: "URL to change-set.json (or .zip with /files entries)"
        required: true

concurrency:
  group: apply-agent-changes
  cancel-in-progress: true

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download change set
        run: |
          set -euo pipefail
          curl -L -f "${{ github.event.inputs.change_set_url }}" -o change-set.json
          if [ ! -s change-set.json ]; then
            echo "Error: Downloaded change set is empty"
            exit 1
          fi

      - name: Validate change set schema
        run: |
          jq -e 'has("files") and (.files | type=="array") and
                 all(.files[]; has("path") and has("content"))' change-set.json >/dev/null

      - name: Apply files (full-file write only)
        id: apply
        run: |
          set -euo pipefail
          while IFS= read -r p; do
            mkdir -p "$(dirname "$p")"
            jq -r --arg p "$p" \
              '.files[] | select(.path==$p) | if .encoding=="base64" then .content | @base64d else .content end' \
              change-set.json > "$p"
          done < <(jq -r '.files[].path' change-set.json)
          BRANCH="agent/${GITHUB_RUN_ID}"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Create branch and commit
        run: |
          set -euo pipefail
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git checkout -b "${{ steps.apply.outputs.branch }}"
          git add -A
          git -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
              commit -m "feat: apply agent change set"
          git push origin "${{ steps.apply.outputs.branch }}"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base main \
            --head "${{ steps.apply.outputs.branch }}" \
            --title "Agent build: change set ${{ github.run_id }}" \
            --body "This pull request was created by the agent Committer workflow.
          
          Change set URL: ${{ github.event.inputs.change_set_url }}
          
          Please review checks and preview." \
            --label agent,auto-fix
