name: Agent smoke

on:
  workflow_dispatch:
    inputs:
      preview_url:
        description: 'Preview URL (e.g. https://complianceloop-site-xxxxx.vercel.app). Paste the latest preview here.'
        required: false
        default: ''

permissions:
  contents: read
  deployments: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run smoke
        env:
          PREVIEW_URL: ${{ inputs.preview_url || secrets.PREVIEW_URL }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_TEAM_SLUG: ${{ secrets.VERCEL_TEAM_SLUG }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_BYPASS_TOKEN: ${{ secrets.VERCEL_BYPASS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node scripts/agent-smoke.mjs
