name: Agent smoke

on:
  workflow_dispatch:
    inputs:
      preview_url:
        description: 'Optional: override PREVIEW_URL (leave blank to use secret)'
        required: false

permissions:
  contents: read

jobs:
  smoke:
    name: smoke
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⛔️ No caching here (avoids lockfile-required error)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Only install if a lockfile exists at repo root
      - name: Install deps at repo root (only if lockfile exists)
        if: hashFiles('package-lock.json') != '' || hashFiles('npm-shrinkwrap.json') != '' || hashFiles('.pnpm-lock.yaml') != ''
        run: npm ci

      # Only install if a lockfile exists in scripts/
      - name: Install deps in /scripts (only if lockfile exists)
        if: hashFiles('scripts/package-lock.json') != '' || hashFiles('scripts/npm-shrinkwrap.json') != '' || hashFiles('scripts/.pnpm-lock.yaml') != ''
        run: npm ci --prefix scripts

      - name: Show Node info
        run: |
          node -v
          npm -v

      - name: Run smoke script
        env:
          # Allow override when dispatching the workflow
          INPUT_PREVIEW_URL: ${{ github.event.inputs.preview_url }}
          # Secrets you added
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
          BYPASS_URL: ${{ secrets.BYPASS_URL }}
          ORIGIN_ALLOWLIST: ${{ secrets.ORIGIN_ALLOWLIST }}
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          # Prefer manual override if provided when running the workflow
          if [ -n "$INPUT_PREVIEW_URL" ]; then
            export PREVIEW_URL="$INPUT_PREVIEW_URL"
          fi

          if [ -z "$PREVIEW_URL" ]; then
            echo "PREVIEW_URL is missing. Set it as a secret or pass an input when running the workflow."
            exit 1
          fi

          # Try known locations for the smoke script
          if [ -f "scripts/smoke.mjs" ]; then
            node scripts/smoke.mjs
          elif [ -f "scripts/smoke.js" ]; then
            node scripts/smoke.js
          elif [ -f "smoke.mjs" ]; then
            node smoke.mjs
          elif [ -f "smoke.js" ]; then
            node smoke.js
          else
            echo "Could not find smoke script (scripts/smoke.mjs|scripts/smoke.js|smoke.mjs|smoke.js)."
            exit 1
          fi
