name: Decide (comment-driven)

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      command:
        description: 'Everything after "/decide ", e.g. set /version "2025-10-15.1"'
        required: true

permissions:
  contents: write
  pull-requests: read
  issues: read

# Prevent overlapping runs per PR comment thread and avoid “canceled” noise
concurrency:
  group: decide-${{ github.event.issue.number || 'manual' }}
  cancel-in-progress: true

jobs:
  run:
    # Only run when:
    # - manually dispatched, OR
    # - a comment was added on a PR by a human (not a bot) AND it contains "/decide "
    if: >-
      (github.event_name == 'workflow_dispatch') ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        !endsWith(github.actor, '[bot]') &&
        contains(github.event.comment.body, '/decide ')
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compose BODY
        id: prep
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "BODY=/decide ${{ inputs.command }}" >> "$GITHUB_ENV"
          else
            printf 'BODY=%s\n' "${{ github.event.comment.body }}" >> "$GITHUB_ENV"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Parse command
        id: parse
        shell: bash
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const body = process.env.BODY || '';
          // /decide <op> </jsonPointer> [value...]
          const m = body.match(/\/decide\s+(\S+)\s+(\/\S+)(?:\s+([\s\S]*))?/);
          if (!m) {
            console.error('No /decide command found'); process.exit(1);
          }
          const [, op, path, value = ''] = m;
          const out = process.env.GITHUB_OUTPUT;
          const marker = 'VAL_' + Math.random().toString(36).slice(2);
          fs.appendFileSync(out,
            `op=${op}\npath=${path}\nvalue<<${marker}\n${value}\n${marker}\n`
          );
          NODE

      - name: Install deps (best-effort)
        run: npm ci || npm i

      - name: Apply decision
        run: |
          node scripts/decisions-apply.mjs \
            --op   "${{ steps.parse.outputs.op }}" \
            --path "${{ steps.parse.outputs.path }}" \
            --value "${{ steps.parse.outputs.value }}"

      - name: Commit changes
        shell: bash
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add decisions.json
            git commit -m "chore(decision): ${{ steps.parse.outputs.op }} ${{ steps.parse.outputs.path }}"
            git push
          else
            echo "No changes to commit"
          fi
