name: Decide (comment-driven)

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      command:
        description: 'Type everything after "/decide ", e.g. set /version "2025-10-15.1"'
        required: true

permissions:
  contents: write
  issues: read

jobs:
  run:
    # For comments, only run if body contains "/decide "
    if: github.event_name == 'workflow_dispatch' || contains(github.event.comment.body, '/decide ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare BODY
        id: prep
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BODY=/decide ${{ inputs.command }}" >> $GITHUB_ENV
          else
            printf "BODY=%s\n" "${{ github.event.comment.body }}" >> $GITHUB_ENV
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Parse command to JSON (Node)
        run: |
          node -e "(() => {
            const fs = require('fs');
            const body = process.env.BODY || '';
            const m = body.match(/\/decide\s+([\s\S]*)/);
            if (!m) { console.error('No /decide command found'); process.exit(1); }
            const tail = m[1].trim();
            const parts = tail.split(/\s+/);
            const op = parts.shift() || '';
            const path = parts.shift() || '';
            const value = tail.slice((op + ' ' + path).length).trim();
            if (!op || !path || !path.startsWith('/')) {
              console.error('Expected: /decide <op> </jsonPointer> <value?>'); process.exit(1);
            }
            fs.writeFileSync('parse.json', JSON.stringify({ op, path, value }), 'utf8');
          })();"

      - name: Export outputs
        id: parse
        run: |
          echo "op=$(node -p \"require('./parse.json').op\")" >> $GITHUB_OUTPUT
          echo "path=$(node -p \"require('./parse.json').path\")" >> $GITHUB_OUTPUT
          echo "value=$(node -p \"require('./parse.json').value\")" >> $GITHUB_OUTPUT
          cat parse.json

      - run: npm ci || npm i

      - name: Apply decision
        run: |
          node scripts/decisions-apply.mjs \
            --op "${{ steps.parse.outputs.op }}" \
            --path "${{ steps.parse.outputs.path }}" \
            --value "${{ steps.parse.outputs.value }}"

      - name: Commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add decisions.json
            git commit -m "chore(decision): ${{ steps.parse.outputs.op }} ${{ steps.parse.outputs.path }}"
            git push
          else
            echo "No changes"
          fi
