name: scaffold-portal
on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create minimal Next.js app files
        run: |
          set -euo pipefail
          mkdir -p apps/portal/app

          cat > apps/portal/package.json <<'EOF'
          {
            "name": "complianceloop-portal",
            "private": true,
            "scripts": {
              "dev": "next dev",
              "build": "next build",
              "start": "next start",
              "lint": "next lint",
              "typecheck": "tsc --noEmit"
            },
            "dependencies": {
              "next": "14.2.5",
              "react": "18.3.1",
              "react-dom": "18.3.1"
            },
            "devDependencies": {
              "@types/node": "^20.12.12",
              "@types/react": "^18.2.79",
              "@types/react-dom": "^18.2.25",
              "eslint": "^8.57.0",
              "eslint-config-next": "14.2.5",
              "typescript": "^5.4.5"
            }
          }
          EOF

          cat > apps/portal/next.config.mjs <<'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = { experimental: { serverActions: { bodySizeLimit: '2mb' } } };
          export default nextConfig;
          EOF

          cat > apps/portal/tsconfig.json <<'EOF'
          {
            "compilerOptions": {
              "target": "ES2022",
              "lib": ["ES2022", "DOM", "DOM.Iterable"],
              "module": "ESNext",
              "moduleResolution": "Bundler",
              "jsx": "preserve",
              "strict": true,
              "noEmit": true,
              "skipLibCheck": true,
              "baseUrl": "."
            },
            "include": ["app", "next-env.d.ts"]
          }
          EOF

          cat > apps/portal/app/layout.tsx <<'EOF'
          export const metadata = { title: "ComplianceLoop Portal" };
          export default function RootLayout({ children }: { children: React.ReactNode }) {
            return (
              <html lang="en">
                <body style={{ margin: 0, fontFamily: "system-ui, sans-serif" }}>{children}</body>
              </html>
            );
          }
          EOF

          cat > apps/portal/app/page.tsx <<'EOF'
          import Link from "next/link";
          export default function Home() {
            return (
              <main style={{ padding: 24 }}>
                <h1>ComplianceLoop Portal</h1>
                <p>Scaffold ready. Phase-2 will add auth, admin, files, and sync.</p>
                <ul>
                  <li><Link href="/portal">/portal (login)</Link></li>
                  <li><Link href="/admin">/admin (stub)</Link></li>
                </ul>
              </main>
            );
          }
          EOF

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          branch: feat/portal-scaffold-min
          title: "feat(portal): minimal Next.js scaffold under /apps/portal"
          body: |
            Adds the minimal files so Vercel can build /apps/portal.
            After merge, https://portal.complianceloop.com should render the starter page.
          commit-message: "feat(portal): add minimal portal scaffold"
          add-paths: |
            apps/portal/**
