name: Smoke

on:
  # Run automatically on PRs that target main (open, update, reopen)
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    # Run for any file change in the PR
    paths:
      - '**'
  # Keep manual trigger for ad-hoc runs (does not count for PR checks)
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Hit Production homepage
        run: |
          set -euo pipefail
          url="https://complianceloop.com"
          code=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 20 "$url")
          echo "HTTP $code from $url"
          # Treat the site as UP unless it's a 5xx or totally unreachable (000)
          if [ "$code" -ge 500 ] || [ "$code" -eq 000 ]; then
            echo "Failing: received $code from $url"
            exit 22
          fi

      - name: Hit Preview redirect (www)
        run: |
          set -euo pipefail
          url="https://www.complianceloop.com"
          code=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 20 "$url")
          echo "HTTP $code from $url"
          if [ "$code" -ge 500 ] || [ "$code" -eq 000 ]; then
            echo "Failing: received $code from $url"
            exit 22
          fi
