name: Vercel + GitHub Inventory (Read-Only)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run inventory
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_SLUG: ${{ secrets.VERCEL_TEAM_SLUG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: ComplianceLoop
        run: node scripts/vercel-inventory.mjs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vercel-inventory
          path: vercel-inventory.json
          if-no-files-found: error
