name: Vercel + GitHub Inventory (Read-Only)

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run inventory
        env:
          # Owner/Repo from context; REPO_FULL = "Owner/Repo"
          REPO_FULL: ${{ github.repository }}
          OWNER: ${{ github.repository_owner }}
          # Prefer your secret GH_TOKEN, fall back to GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.GH_TOKEN || github.token }}
          # Vercel is optional; if missing or blocked we'll continue gracefully
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_TEAM_SLUG: compliance-loop
        run: node scripts/vercel-inventory.js
